version: '2'

services: 
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - '.:/src'

  ide:
    image: codercom/code-server:1.621
    command: --allow-http --no-auth --user-data-dir /data --port 8888 /src
    volumes:
      - './:/src'
      - './data:/data'
      - '~/.gitconfig:/etc/gitconfig'
      - '~/.ssh:/home/coder/.ssh'
    ports:
      - '8888:8888'

  db:
    image: postgres:9-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: test
