version: '2'

services: 
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - '.:/src'

  db:
    image: postgres:14.6-alpine
    ports:
      - '5432:5432'
    command: "-c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    environment:
      POSTGRES_USER: test
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: test
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"

  adminer:
    image: adminer:4
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
      
  ide:
    build: 
      context: .
      dockerfile: docker/ide/Dockerfile
    volumes:
      - './:/src'
      - './data:/data'
      - '~/.gitconfig:/etc/gitconfig'
      - '~/.ssh:/home/coder/.ssh'
    ports:
      - '8888:8888'
